AFNetworking/AFNetworking

UIKit+AFNetworking/UIAlertView+AFNetworking.m
` find . -name \*.m | xargs genstrings -o .` generate the following warning: 
Warning: Key "Dismiss" used with multiple comments "UIAlert View Cancel Button Title" & "UIAlertView Cancel Button Title"
=> fix genstrings warning in UIAlertView+AFNetworking

UIKit+AFNetworking/UIButton+AFNetworking.m
I've found a pair of typos that prevented the UIButtons from reporting on the failed image downloads; both of them have been corrected.
=> UIButton+AFNetworking. The methods that asynchronously download images have started to properly report on the failures.

AFNetworking/AFURLSessionManager.m
Issue details at #2476. Now matches tasks with `AFURLSessionManager`s by setting all tasks' `taskIdentifier`s to the stringified address of the manager.
=> Network indicator no longer spins forever when using >1 session manager

UIKit+AFNetworking/UIAlertView+AFNetworking.m
I found a minor problem at following methods which are in category extension class for UIAlertView.
* ``` + (void)showAlertViewForTaskWithErrorOnCompletion:(NSURLSessionTask *)task
delegate:(id)delegate
cancelButtonTitle:(NSString *)cancelButtonTitle
otherButtonTitles:(NSString *)otherButtonTitle, ... ```
* ``` + (void)showAlertViewForRequestOperationWithErrorOnCompletion:(AFURLConnectionOperation *)operation
delegate:(id)delegate
cancelButtonTitle:(NSString *)cancelButtonTitle
otherButtonTitles:(NSString *)otherButtonTitle, ...```  
For instance, if the ```otherButtonTitles, ...``` variable argument is set to ```@"Button1", @"Button2", @"Button3", nil``` , the alertView should be displayed like this.  
However,  these methods display only first of variable arguments (``` @"Button1" ```) …
=> Display all of variable arguments which are specified as otherButtonTitles

AFNetworking/AFURLRequestSerialization.h, AFNetworking/AFURLRequestSerialization.m
parameters maybe a raw string or other things , when parameters is String , we do need twice cast in Swift  (parameters as AnyObject) as String. So, I think it's comfortable to change parameters's type to id
=> make parameters accepting other types

AFNetworking/AFHTTPRequestOperationManager.h, AFNetworking/AFHTTPSessionManager.h, AFNetworking/AFNetworkReachabilityManager.h, AFNetworking/AFURLConnectionOperation.h, AFNetworking/AFURLSessionManager.h
`NS_DESIGNATED_INITIALIZER` is not included in Xcode 5. Since AFNetworking doesn't have a common #import for all headers, I just inserted a definition for it into each file that uses it. A common header would be better, of course!
I'm submitting this primarily so that people using Xcode 5 can check it. I'm not anymore. You might want to add a common header instead, or even drop support for Xcode 5. Whatever. :) Something _like_ this is necessary if Xcode 5 compatibility is to be maintained.
See: http://stackoverflow.com/questions/24119896/ns-designated-initializer-expected-colon and issue #2555.
=> Add NS_DESIGNATED_INITIALIZER for earlier versions of Xcode.

AFNetworking/AFURLSessionManager.m
This is a re-opening of #2459, as requested by @mattt [here](https://github.com/AFNetworking/AFNetworking/pull/2459#issuecomment-74393321).
----
The AFNetworkActivityIndicatorManager is broken for iOS 7, as of #2411. (See #2458.)
This swizzle-fix for #1477 used to assume that all `NSURLSessionTask` instances had a superclass named `NSURLSessionTask`. Unfortunately, that is not true on iOS 7 devices.
We still need to somehow swizzle a superclass of all `NSURLSessionTask`s, though. On iOS 7, one of those superclasses is `__NSCFLocalSessionTask`, which is `NSURLSessionDataTask`'s superclass. This is a way to do it without explicitly mentioning or calling any private API.
However, it does end up adding and swizzling methods on `__NSCFLocalSessionTask`. Is this legal? I hope so, but …
=> Fix AFNetworkActivityIndicatorManager for iOS 7...dubiously

UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m, UIKit+AFNetworking/UIAlertView+AFNetworking.h, UIKit+AFNetworking/UIAlertView+AFNetworking.m
See Issue #2119.
It seems that a couple of references to unsupported APIs in extensions were missed. I'd really appreciate a fix because I can't properly build my extension at the moment.
Credit goes to @jpmhouston.
=> Guard for unsupported features of iOS 8 extensions

Tests/Tests/AFSecurityPolicyTests.m
It appears to be a copy paste error from the test above (
line 533 of `testPolicyWithPinningModeIsSetToNotAllowInvalidSSLCertificates`).
=> Fix for broken test

AFNetworking/AFURLSessionManager.m
Changes posted in https://github.com/AFNetworking/AFNetworking/issues/2638#issuecomment-94174154
=> [issue #2638] Fixes 10.8 / iOS 6 _OBJC_CLASS_$_NSURLSessionDataTask crash

Tests/AFNetworking Tests.xcodeproj/project.pbxproj
I've seen this many times before. Something goes wrong when updating a CocoaPods installation in some way and you can end up with this invalid search path. I caught the issue in the Travis CI output from #2716. This will fix up that issue.
cc: @kcharwood
=> Fixed OS X Test linker warning for bad framework search path

Rakefile
#2702 helped me discover our unit tests aren't running on all of the available simulators installed on Travis.
This PR attempts to rectify that by using the `-destination` parameter for Xcode build. You can get the list of available simulators on a machine by using `xcrun simctl list`, and I have some regex to pull out a simulator for each OS version.
This may still occasionally cause Travis to fail because of the issues with the reachability tests that are fixed in #2702. 
cc @cnoon @mattt  @kylef
=> Updated Rakefile to run multiple OS versions of unit tests

AFNetworking/AFURLSessionManager.m, Tests/AFNetworking Tests.xcodeproj/project.pbxproj, Tests/Tests/AFURLSessionManagerTests.m
The `_AFStateObserving` category on `NSURLSessionTask` was recently changed (2.5.3) to remove a `dispatch_once` block.  I'm not sure what the intent of this change was, but one of the side effects is that the swizzling gets run multiple times (for every initialized subclass of `NSURLSessionTask`) and effectively "flip flops" the implementations of the original methods with the swizzled methods.
If this gets called an odd number of times, it happens to work.  However, if it gets called an even number of times, the net result is that the swizzled methods are never run.
If I log the classes this method is called on, here's the result I see when I first use a data task:
```
2015-05-06 14:17:00.788 class=__NSCFLocalDataTask, taskClass=__NSCFLocalSessionTask
2015-05-06 14:17:00.793 …
```
=> _AFStateObserving Swizzling Implementation is Wrong

Tests/AFNetworking Tests.xcodeproj/project.pbxproj, Tests/Tests/AFUIActivityIndicatorViewTests.m, Tests/Tests/AFUIRefreshControlTests.m, UIKit+AFNetworking/UIActivityIndicatorView+AFNetworking.m, UIKit+AFNetworking/UIRefreshControl+AFNetworking.m
View that  observe AFNetworkingOperationDidStartNotification such as UIActivityIndicatorView may crash because View does not remove Observer for AFNetworkingOperationDidStartNotification.
=> AFNetworkingOperationDidStartNotification crash

Tests/Tests/AFUIActivityIndicatorViewTests.m, UIKit+AFNetworking/UIActivityIndicatorView+AFNetworking.m, UIKit+AFNetworking/UIRefreshControl+AFNetworking.m
This introduces associated objects so notifications can be cleared in dealloc without clobbering the class's dealloc.
=> Fix issue #2739

AFNetworking/AFSecurityPolicy.h, AFNetworking/AFSecurityPolicy.m, Tests/Tests/AFSecurityPolicyTests.m
We have identified an issue that prevents `validatesCertificateChain` from validating the entire chain if a developer mistakenly pins duplicate certificates.
The fix is to simply ensure pinned certificates does not contain any duplicates. This does not represent an actual security vulnerability, as the duplicate certificates still need to be present in the certificate chain of the server trust.
In addition, this problem may also go away in a future version, if we deprecate the `validatesCertificateChain` property as discussed in #2744 
For now, we can put this fix into 2.5.5.
=> Eliminated duplicated pinned certificates

README.md
Add startMonitoring call to README to clarify that startMonitoring still need to be called when using the block based reachability callback method
=> Add startMonitoring call to README under block based reachability call

Rakefile
Once I got the beta on my machine, I saw the following output from `xcrun simctl list`
```
== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
Resizable iPhone (com.apple.CoreSimulator.SimDeviceType.Resizable-iPhone)
Resizable iPad (com.apple.CoreSimulator.SimDeviceType.Resizable-iPad)
== Runtimes ==
iOS 7.1 (7.1 - 11D167) …
```
=> Fixed issue where xcrun was returning unavailable simulators

AFNetworking/AFURLConnectionOperation.m, AFNetworking/AFURLRequestSerialization.m, AFNetworking/AFURLResponseSerialization.m, Example/Classes/Controllers/GlobalTimelineViewController.m, Tests/Tests/1.0 Tests/AFHTTPClientTests.m, Tests/Tests/AFSecurityPolicyTests.m
1. NSDictionary  +dictionaryWithObject:obj forKey:key -> @{key : obj}
2. NSDictionary -objectForKey:key -> dict[key]
3. NSArray -objectForKey:0 -> [array firstObject] (in AFURLRequestSerialization.m where it makes sense).
4.NSArray +arrayWithObject[x] -> @[x]
=> Minor changes to support modern Objective-C syntax.

Tests/AFNetworking Tests.xcodeproj/project.pbxproj, Tests/Tests/AFHTTPRequestSerializationTests.m, Tests/Tests/AFUIActivityIndicatorViewTests.m, Tests/Tests/AFUIImageViewTests.m, Tests/Tests/AFUIRefreshControlTests.m, Tests/Tests/AFURLSessionManagerTests.m, UIKit+AFNetworking/UIImageView+AFNetworking.h, UIKit+AFNetworking/UIImageView+AFNetworking.m
When UIImageView+AFNetworking successfully retrieves an image from the cache, the URL request was not being provided to the success block along with the image. This meant that there was no way to compare retrieved image's URL with the URL that should be displayed.
=> Provide URL request to the success block when images are retrieved from cache

AFNetworking/AFHTTPSessionManager.h
```Objective-C
/**
The URL used to monitor reachability, and construct requests from relative paths in methods like `requestWithMethod:URLString:parameters:`, and the `GET` / `POST` / et al. convenience methods.
*/
@property (readonly, nonatomic, strong) NSURL *baseURL;
```
In the `- (instancetype)initWithBaseURL:(NSURL *)` method, `self.reachabilityManager` doesn't use the baseURL. I know I can adjust `self.reachabilityManager` later with `"initWithReachability`. But the description confused me. Is this a problem?
=> problem with baseURL

AFNetworking/AFNetworkReachabilityManager.m, AFNetworking/AFURLConnectionOperation.m
Fixes the `Method override for the designated initializer of the superclass '-init' not found` warnings on Xcode 7 beta 2. 
This is an alternative to https://github.com/AFNetworking/AFNetworking/pull/2789 , if we think `init` should be unavailable in these cases.
=> Fix "method override not found" warnings on Xcode 7b2

AFNetworking/AFSecurityPolicy.h, AFNetworking/AFSecurityPolicy.m, Tests/AFNetworking Tests.xcodeproj/project.pbxproj, Tests/Tests/AFSecurityPolicyTests.m
As discussed in #2744, I have removed certificate chain validation as a feature in `AFSecurityPolicy`. After a community discussion as well as a conversation with the security team at Apple, there are no specific advantages to maintaining this feature going forward.
Starting with this pull request, a security policy will allow a server trust if any of the pinned certificates meeting the security requirements of the policy. 
In addition, I have completely refactored the security policy tests, and grouped them in a way that is more readable and more maintainable going forward. I would love some eyes on those tests and see if we can come up with any more, especially negative test cases.
We'll get this in first, then move on to bringing in public key hash pinning.
=> Removed Certificate Chain Validation

AFNetworking/AFURLConnectionOperation.h, AFNetworking/AFURLConnectionOperation.m, Example/AFNetworking iOS Example.xcodeproj/project.pbxproj, Example/Classes/Models/Post.m, Example/Classes/Models/User.h, Example/Classes/Models/User.m, Example/Today Extension/Info.plist, Example/Today Extension/MainInterface.storyboard, Example/Today Extension/TodayViewController.h, Example/Today Extension/TodayViewController.m, UIKit+AFNetworking/AFNetworkActivityIndicatorManager.h, UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m, UIKit+AFNetworking/UIAlertView+AFNetworking.h, UIKit+AFNetworking/UIAlertView+AFNetworking.m
clang will silence availability errors in classes and methods that are also unavailable to the target.  The following have been made unavailable to app extensions:
- `AFNetworkActivityIndicatorManager` class
- `UIAlertView` category methods
- `AFURLConnectionOperation setShouldExecuteAsBackgroundTaskWithExpirationHandler:`
Benefits of change:
- Fixes CocoaPods support for App Extensions.
- Allows single framework to be used in app.
- Eliminates the need for `AF_APP_EXTENSIONS`.
=> Allow same library for app and extensions.

AFNetworking/AFURLRequestSerialization.m, Tests/Tests/AFHTTPRequestSerializationTests.m
Since watchOS requires us to use `stringByAddingPercentEncodingWithAllowedCharacters`, we've migrated over to that. We're also using the logic that has been baked in to AlamoFire.
Note this does have one backwards compatible issue. `/` and `?` are no longer encoded in the query parameters, per RFC 3986.
```
In RFC 3986 - Section 3.4, it states that the "?" and "/" characters should not be escaped to allow
query strings to include a URL. Therefore, all "reserved" characters with the exception of "?" and "/"
should be percent-escaped in the query string.
- parameter string: The string to be percent-escaped.
- returns: The percent-escaped string.
```
@cnoon want to take a look?
=> Convert query escapes to `stringByAddingPercentEncodingWithAllowedCharacters`

AFNetworking/AFURLConnectionOperation.h
When using cocoapods, we need fix this to avoid compile error.
See http://stackoverflow.com/questions/27267865/strong-dispatch-queue-t-in-cocoapods-library
=> use OS_OBJECT_USE_OBJC instead of OS_OBJECT_HAVE_OBJC_SUPPORT

Tests/Tests/AFSecurityPolicyTests.m
If you go to the iOS example, just execute the following:
```
[AFAppDotNetAPIClient sharedClient].securityPolicy = [AFSecurityPolicy defaultPolicy];
[AFAppDotNetAPIClient sharedClient].securityPolicy.allowInvalidCertificates = YES;
```
and AFNetworking will no longer work.
=> Setting `allowInvalidCertificates` to `YES` cause AFNetworking to no longer work. UPDATE: Set `validatesDomainName` to NO to get working.

AFNetworking/AFURLSessionManager.m
I have integrated AWS analytics(2.1.1), Facebook SDK(4.1.0) and AFNetworking(2.5.4) in one application. but app is crashing while launching itself
tried many ways to resolve this
1. commented line number 357 in screen shot its working fine
2. downgrade to AFNetworking 2.4.0 working fine.
=> AWS analytics for iOS app crash in AFNetworking

AFNetworking/AFURLConnectionOperation.m
I'm using AFNetworking (2.5.0) via Cocoapod in an iOS >7.0 application.
I need to download a binary file so i configured the `outputStream` property
```objective-c
AFHTTPRequestOperation *op = [self.operationManager GET:url
parameters:nil
success:^(AFHTTPRequestOperation *operation, id responseObject) {
} failure:^(AFHTTPRequestOperation *operation, NSError *error) {
}];
op.outputStream = [NSOutputStream outputStreamToFileAtPath:tempPath append:YES];
````
90% of the times it works correctly, but in some case the line AFURLConnectionOperation.m@655 became false (i put a breakpoint) and the library enters in an endless loop and no failure blocks are called.
I put here the current implementation of the method
````objective-c
NSUInteger length = [data length];
while (YES) {
NSInteger …
```
=> hasSpaceAvailable become "false" and no failure blocks are called

AFNetworking/AFHTTPSessionManager.m, AFNetworking/AFSecurityPolicy.m, AFNetworking/AFURLRequestSerialization.m, AFNetworking/AFURLResponseSerialization.m, AFNetworking/AFURLSessionManager.m, Example/iOS Example/Views/PostTableViewCell.m, UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m
Minor change to return `instancetype` instead of `id` for the initialises and copy methods to indicate that it's the same type.
=> Use `instancetype` where applicable

AFNetworking/AFHTTPRequestOperationManager.h, AFNetworking/AFURLSessionManager.h
As per #2930, this won't build for watchOS 2 otherwise.
I know this is fixed for AFNetworking 3 since we dropped older OS supports, I'd suggest we add this for the next patch/maintenance release.
/cc @kcharwood
=> Switch to OS_OBJECT_USE_OBJC

AFNetworking/AFHTTPRequestOperationManager.m, AFNetworking/AFHTTPSessionManager.m, AFNetworking/AFSecurityPolicy.h, AFNetworking/AFSecurityPolicy.m, Tests/Tests/AFSecurityPolicyTests.m
When I tried to copy the AFHTTPSessionManager the securityPolicy doesn't get copied with it.
=> AFHTTPSessionManager copying securityPolicy not getting copied

Tests/Tests/AFNetworkActivityManagerTests.m, Tests/Tests/AFTestCase.h, Tests/Tests/AFTestCase.m, UIKit+AFNetworking/AFNetworkActivityIndicatorManager.h, UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m
This allows us to support the recommendation from the Apple HIG, which is short requests that last less than a couple of seconds should not trigger the network activity indicator.
Originally brought up in #3086 by @lubiluk 
cc @cnoon @kylef @jshier for review.
=> A refactored version of #3086 allowing a delayed start to the network activity indicator

Tests/Tests/AFNetworkReachabilityManagerTests.m, Tests/Tests/AFUIActivityIndicatorViewTests.m, Tests/Tests/AFUIImageViewTests.m, Tests/Tests/AFURLSessionManagerTests.m
Multiple tests were causing some race condition issues with travis ci. I've verified they are false positives, so I am removing them for now to improve testing reliability.
=> Improved testing reliability for continuous integration

AFNetworking/AFNetworkReachabilityManager.m
This is an alternative implementation of a previous attempt to fix a race condition in reachability notifications, particularly with domain-name-based associations. However, we encountered cases where the status-change callback could still receive notifications out of order, due to one path executing the callback immediately on the runloop thread and the other queuing the callback onto the GCD main queue (which is _serviced_ by the same run loop, but the order in which queue blocks and other run loop callbacks are executed is not easy to determine).
I broke this into two commits: The first is the fix for the issue, by sending all callback notifications through the GCD main queue, just as the NSNotifications were being sent. This is the code we've been using for a few weeks and it has …
=> Fixed race condition in reachability callback delivery

AFNetworking/AFURLSessionManager.h
=> Fixed swift interop issue that prevented returning a nil NSURL for a download task

Tests/Tests/AFUIImageViewTests.m, UIKit+AFNetworking/UIImageView+AFNetworking.m
=> Fixed crash that occurred if you passed a nil URL to the image view

AFNetworking/AFNetworkReachabilityManager.m
=> Fixed clang analyzer warning suppression that prevented building under some project configurations

UIKit+AFNetworking/AFImageDownloader.m
The active task count was only being decremented after success. Once the number of failures reaches the maximumActiveDownloads, no more tasks were being started.
=> Fixed AFImageDownloader stalling after numerous failures

AFNetworking/AFURLRequestSerialization.m
may cause inputStream read more bytes than the setting value numberOfBytesInPacket
=> Fixed bug in AFMultipartBodyStream that may cause the input stream to read more bytes than required.

AFNetworking/AFSecurityPolicy.h, AFNetworking/AFSecurityPolicy.m, Tests/Tests/AFSecurityPolicyTests.m
Pinned certificates were deduplicated anyway, so let’s make it clear directly in the API.
=> Changed `pinnedCertificates` type in `AFSecurityPolicy` from `NSArray` to `NSSet`

AFNetworking/AFSecurityPolicy.h, AFNetworking/AFURLRequestSerialization.h, AFNetworking/AFURLResponseSerialization.h, AFNetworking/AFURLSessionManager.h
Since v3 is going to require Xcode 7, adding generics support would be nice. Who knows, it might even catch some lingering bugs. 😝
=> Added support for Objective-C light weight generics

AFNetworking/AFNetworkReachabilityManager.h, AFNetworking/AFNetworkReachabilityManager.m, Tests/Tests/AFNetworkReachabilityManagerTests.m
Added IPv6 support for Reachability based on the work from @SAMUKEI in #3171
=> Added support for IPv6 to Reachability

AFNetworking/AFHTTPSessionManager.h, AFNetworking/AFHTTPSessionManager.m, AFNetworking/AFURLSessionManager.h, AFNetworking/AFURLSessionManager.m, Example/Classes/Models/Post.m, Tests/Tests/AFHTTPSessionManagerTests.m, Tests/Tests/AFNetworkActivityManagerTests.m, Tests/Tests/AFNetworkReachabilityManagerTests.m, Tests/Tests/AFURLSessionManagerTests.m, UIKit+AFNetworking/UIWebView+AFNetworking.m
These changes expose a simpler, block based progress reporting API, while maintaining the ability for more advanced features using KVO on NSProgress.
Issues #3158 and #3163 got me thinking that progress **_was easier_** to use with old NSURLConnection based API's, and we shouldn't force anyone to use KVO for progress updating, so I decided to take a stab at implementing a block based approach, while also streamlining the accessors for individual upload and download progress.
Note that `NSURLSessionTask` sees progress as two distinct items: upload progress and download progress, as reported by `countOfBytesExpectedToReceive`, `countOfBytesReceived`, `countOfBytesExpectedToSend`, and `countOfBytesSent`. Therefore, I've decided to track these two things independently with two distinct …
=> New Progress Reporting API using `NSProgress`

README.md
Looks like this functionality was removed when the Rakefile was deleted in e0815da
=> Remove testing from command line in readme

AFNetworking.xcodeproj/project.pbxproj, Tests/Tests/AFUIButtonTests.m, Tests/Tests/AFUIImageViewTests.m, UIKit+AFNetworking/AFImageDownloader.h, UIKit+AFNetworking/AFImageDownloader.m, UIKit+AFNetworking/UIButton+AFNetworking.m, UIKit+AFNetworking/UIImageView+AFNetworking.m
Alternate Solution for #3214 
See https://github.com/Alamofire/AlamofireImage/issues/55 for details
@cnoon which one do you think is better? I think I like approach better, but it does add a new API method to the downloader. Should still be backwards compatible.
=> Fixed race condition with ImageView/Button image downloading when starting/cancelling/starting the same request

Tests/Tests/AFUIButtonTests.m, UIKit+AFNetworking/UIButton+AFNetworking.m
Background image did not change when `setBackgroundImageForState` called as `setImage` was used instead of `setBackgroundImage`.
=> Button image changed instead of background image

AFNetworking/AFURLSessionManager.m
As long as there is already a `downloadTaskDidResume` block, this invocation should be removed.
=> Fixed crash in `AFURLSessionManager` when resuming download task.

AFNetworking/AFURLResponseSerialization.m
… as well as a couple other missing preprocessor checks for tvOS and watchOS in that class. See: https://github.com/AFNetworking/AFNetworking/issues/3228
=> Fixed `AFImageResponseSerializer` serializing on watchOS 

AFNetworking/AFURLSessionManager.m
version: 3.0.3
file: AFURLSessionManager.m
[line: 747,748](https://github.com/AFNetworking/AFNetworking/blob/3.0.3/AFNetworking/AFURLSessionManager.m#L747-L748)
AFNSURLSessionTaskDidResumeNotification was removed twice, why?
=> Fixed issue where `AFNSURLSessionTaskDidResumeNotification` was removed twice

README.md
Now AFHTTPRequestSerializer always requires error parameter, but the examples on README.md don't follow the change.
=> Add error parameter to the examples of AFHTTPRequestSerializer on README.md

AFNetworking/AFURLResponseSerialization.m, Tests/Tests/AFJSONSerializationTests.m
The NSJSONSerialization bug with Unicode character escape codes has been fixed in iOS 7, see http://openradar.appspot.com/radar?id=2397401#ag9zfm9wZW5yYWRhci1ocmRyFAsSB0NvbW1lbnQYgICAgIDdwwgM
Removing the NSData -> NSString -> NSData roundtrip is also likely a nice performance boost.
=> Removed workaround for NSJSONSerialization bug that was fixed in iOS 7

AFNetworking/AFURLRequestSerialization.h, AFNetworking/AFURLRequestSerialization.m, Tests/Tests/AFHTTPRequestSerializationTests.m
I need custom AFHTTPRequestSerializer to feet for our api
case is : 
in post request, some of url parameter must use url-formed format to apend in the url
so I need to use c method AFQueryStringFromParameters() but saw it is not open , 
can this be exposed in 3.0.0?
=> Exposed `AFQueryStringFromParameters` and `AFPercentEscapedStringFromString` for public use.

AFNetworking/AFURLSessionManager.m
iOS8.0, 9.0 is OK, but progress block not called at all，iOS7.0 #3282
=> Fixed issue where download progress would not be reported in iOS 7

AFNetworking/AFNetworkReachabilityManager.m
The current version of `AFNetworkReachabilityManager` fixes some static analyzer warnings by using `#ifndef __clang_analyzer__` to hide the errors. This PR removes that conditional code in favor of fixing the analyzer issue.
Instead of bridging the reachability reference to ARC, this PR sets the type of `networkReachability` to `SCNetworkReachabilityRef`, which not only allows for cleaner memory management as far as the analyzer is concerned, but also gets rid of a lot of unnecessary bridging further into the file.
=> Fixed static analyzer warnings on AFNetworkReachabilityManager

Tests/Tests/AFAutoPurgingImageCacheTests.m
This PR fixes the auto-purging image cache tests that were broken by merging #3344. I've verified the changes are accurate. The logo image is 850 x 300 px with a pixel size of 4 bytes which totals 1020000 bytes.
=> Fix - Image Cache Tests

AFNetworking/AFHTTPSessionManager.h, AFNetworking/AFURLSessionManager.h, UIKit+AFNetworking/AFAutoPurgingImageCache.h, UIKit+AFNetworking/AFImageDownloader.h
Turned on some more warnings in Xcode and these warnings popped up.
=> Updated documentation to match method names and correct compiler warnings

AFNetworking/AFHTTPSessionManager.h, AFNetworking/AFURLSessionManager.h, UIKit+AFNetworking/AFAutoPurgingImageCache.h, UIKit+AFNetworking/AFImageDownloader.h
These compiler warnings for incorrect parameters in the function documentation don't seem to appear when building AFNetworking, but they do appear in an iOS project I use with AFNetworking as a dependency (via Pods).
=> Resolved compiler warnings for documentation errors

AFNetworking/AFURLResponseSerialization.m, Tests/Tests/AFHTTPResponseSerializationTests.m
If a server returned a 204/205 with no response content type and no response data, the response serializer would fail. This patch allows response serialization to continue without error if no response content type header is defined, and there are zero bytes of response of data.
If the server returns a response content type header OR response data, the serializer will respect the old serialization logic. This means that if a response content type is listed in the header, we are expecting some type of data response.
This patches #2797
=> Fixed status code 204/205 handling

AFNetworking/AFURLSessionManager.m
* We explicitly used @"new" in `change`, I think it's better to use
platform defined constant.
This is a duplicate one for [PR#3352](https://github.com/AFNetworking/AFNetworking/pull/3352). My repository was messed up during the weekend and the PR was closed.
=> Use `NSKeyValueChangeNewKey` constant in change dictionary rather than hardcoded string.

Tests/Tests/AFImageDownloaderTests.m, UIKit+AFNetworking/AFImageDownloader.m
A continuation of #3356 and #3343
=> Fixed crash if bad URL was passed into the image downloader

AFNetworking.xcodeproj/project.pbxproj, Tests/Tests/AFImageResponseSerializerTests.m
Added a new test class specifically for AFImageResponseSerializer along with several tests.
=> AFImageResponseSerializer tests

AFNetworking/AFURLSessionManager.m, Tests/Tests/AFHTTPSessionManagerTests.m
As first discussed in #3409, there appear to be cases where returning `NSURLSessionAuthChallengeRejectProtectionSpace` does not prevent the request from succeeding in some cases.
A few of us have starting to dig in on this issue. @0xced has seen behavior where the existing code does work in some cases, leading us to believe there may be some issues here related to the TLS cache under the hood that we do not control. However, using `Cancel` instead does give us deterministic control.
The [original intent](https://github.com/AFNetworking/AFNetworking/pull/3169) of moving to `RejectProtectionSpace` was to provide a better error message to the developer to distinguish between a manual cancel and an SSL pinning failure.
I've created a simple playground demonstrating the issue: …
=> Reverted `NSURLSessionAuthChallengeDisposition` to `NSURLSessionAuthChallengeCancelAuthenticationChallenge` for SSL Pinning

AFNetworking/AFURLSessionManager.m
`AFTaskStateChangedContext` is not used in AFN 3
=> remove unused `AFTaskStateChangedContext`

LICENSE
Updated to a different unicode dash (`U+002D` rather than `U+2013`) so that text is parsed correctly by markdown (when converting the CocoaPods `Acknowledgements.markdown` to HTML). 
Prior to the adjustment, this was the result upon conversion to HTML:
With the adjustment, issue corrected:
=> Updated character

AFNetworking/AFHTTPSessionManager.h
This closes #3412.
The documentation on `AFHTTPSessionManager`, *Methods to Override* section  states that...
> To change the behavior of all data task operation construction, which is also used in the `GET` / `POST` / et al. convenience methods, override `dataTaskWithRequest:completionHandler:` 
But that is no longer accurate, since these convenience methods now go through the new 
`dataTaskWithRequest:uploadProgress:downloadProgress:completionHandler:`. Therefore, overriding `dataTaskWithRequest:completionHandler:` will have no effect since it will never be called.
This PR updates the documentation to reflect the fact that the method to override is now `dataTaskWithRequest:uploadProgress:downloadProgress:completionHandler:`.
=> Updates `AFHTTPSessionManager` documentation to reflect v3.x changes

AFNetworking/AFURLSessionManager.h, Tests/Tests/AFHTTPSessionManagerTests.m, Tests/Tests/AFUIActivityIndicatorViewTests.m, Tests/Tests/AFUIRefreshControlTests.m, Tests/Tests/AFURLSessionManagerTests.m, UIKit+AFNetworking/AFImageDownloader.m
It's dangers to leave `dataTaskWithRequest:completionHandler:` method without deprecated mark, as this method is now overloaded, and calling a different one, it breaks compatibility with previous overridden methods.
=> Added deprecated attribute to  `dataTaskWithRequest:completionHandler:`

AFNetworking/AFURLRequestSerialization.m, Tests/Tests/AFHTTPRequestSerializationTests.m, Tests/Tests/AFJSONSerializationTests.m
This is a fix for an intermittent crash bug which is likely to occur in any app which sets header values with dynamic values over around six characters long. These strings are reference counted, but the counting goes wrong because the owner, the headers dictionary, is not a thread-safe collection, but will be used from multiple threads in normal use of the AFNetworking library. The frequency of crashes increases greatly if you have a header which needs to be updated constantly. The crashes appear in areas of the app which are almost always completely unrelated, but often have deallocation in the stack trace.
This fix has been included in a shipping app with ~400k daily launches since the end of February, and has reduced our crash rate to almost nil.
I have included a unit test which …
=> Fixed crashes due to race conditions with NSMutableDictionary access in AFHTTPRequestSerialiser

AFNetworking.xcodeproj/project.pbxproj
This helps prevent the problem described in #3398.
=> require app extension api only on watchOS

UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m
I found '[self didChangeValueForKey:@"currentState"];' is outsite of the if{} scope,that confused me, maybe it should be insite.
=> Moved `[self didChangeValueForKey:@"currentState"]` into correct scope

AFNetworking/AFNetworkReachabilityManager.h
Fixed issue where NS_UNAVAILABLE is not reported to calling code as it was previously just in the .m file - this allows the compiler to generate a build error when using the init method
=> Fixed issue where `NS_UNAVAILABLE` is not reported for `AFNetworkReachabilityManager`

AFNetworking/AFURLSessionManager.m, Tests/Tests/AFHTTPSessionManagerTests.m, Tests/Tests/AFURLSessionManagerTests.m
Setting the expectation to nil after it is fulfilled in order to avoid `*** Assertion failure in -[XCTestExpectation fulfill]` was just hiding the real issue.
=> Fix progress handlers called with fractionCompleted == 1 several times

Tests/Tests/AFImageDownloaderTests.m, Tests/Tests/AFTestCase.h, Tests/Tests/AFTestCase.m, Tests/Tests/AFUIActivityIndicatorViewTests.m, Tests/Tests/AFUIButtonTests.m, Tests/Tests/AFUIImageViewTests.m, Tests/Tests/AFUIRefreshControlTests.m, Tests/Tests/AFUIWebViewTests.m, Tests/Tests/AFURLSessionManagerTests.m
There was some repetition in URL creation for unit tests. Extracting the common URLs (png, jpeg, delay, status code) makes it easier run the test suites on a local copy of httpbin with the `python -m httpbin.core` command.
=> Extract common URLs into AFTestCase

AFNetworking/AFHTTPSessionManager.h, AFNetworking/AFHTTPSessionManager.m, Tests/Tests/AFHTTPSessionManagerTests.m
Setting a security policy configured with `AFSSLPinningModeCertificate` or `AFSSLPinningModePublicKey` on a AFHTTPSessionManager instance configured with an insecure `http` base URL was valid. Requests made with this manager would always succeed since the `-[AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:]` would never be called and thus the security policy would never be evaluated.
Setting a security policy configured with `AFSSLPinningModeCertificate` or `AFSSLPinningModePublicKey` on a AFHTTPSessionManager instance configured with an insecure `http` base URL will throw an exception. This will force the manager to be configured with a secure `https` URL.
Note that properly configuring App Transport Security (ATS) would also solve this issue since insecure …
=> AFHTTPSessionManager now throws exception if SSL pinning mode is set for non https sessions

AFNetworking/AFURLResponseSerialization.m, Tests/Tests/AFCompoundResponseSerializerTests.m, Tests/Tests/AFImageResponseSerializerTests.m, Tests/Tests/AFJSONSerializationTests.m, Tests/Tests/AFPropertyListResponseSerializerTests.m
Reference to #3537 
NSCopying documentation states the following:
> Implement NSCopying by invoking the superclass’s copyWithZone: when NSCopying behavior is inherited. If the superclass implementation might use the NSCopyObject function, make explicit assignments to pointer instance variables for retained objects.
This change implements this behavior, and properly copies the super properties.
=> Fixed issue where response serializers did not inherit super class copying

AFNetworking.xcodeproj/project.pbxproj, AFNetworking/AFURLRequestSerialization.m, AFNetworking/AFURLResponseSerialization.m, AFNetworking/AFURLSessionManager.m, Tests/Tests/AFJSONSerializationTests.m, Tests/Tests/AFPropertyListRequestSerializerTests.m, Tests/Tests/AFPropertyListResponseSerializerTests.m
=> Handle Error Pointers according to Cocoa Convention

Tests/Tests/AFUIWebViewTests.m, UIKit+AFNetworking/UIWebView+AFNetworking.m
This should fix #3724 and any header-related issue in the future.
After this changes, the entire `request`, instead of only the `URL`, will be used to construct the `dataTask`.
Test case is added.
=> Fixed issue where UIWebView extension did not preserve all of the request information

UIKit+AFNetworking/AFImageDownloader.m
See #3594.
Rebased with master here to get proper test coverage before merging, and added comments.
=> Fixed crash around customizing NSURLCache size for < iOS 8.2

AFNetworking/AFURLRequestSerialization.m, Tests/Tests/AFJSONSerializationTests.m
Fixes #3711
The `NSURLErrorCannotDecodeContentData` code is not ideal, but `AFURLRequestSerializationErrorDomain` should define its own error codes anyway.
=> Fixed crash when passing invalid JSON to request serialization

AFNetworking/AFSecurityPolicy.m
Removed ambiguous array creation in `AFSecurityPolicy`. According to [SecTrustCreateWithCertificates] (https://developer.apple.com/library/mac/documentation/Security/Reference/certifkeytrustservices/#//apple_ref/c/func/SecTrustCreateWithCertificates) documentation:
> If you want to specify only one certificate, you can pass a SecCertificateRef object; otherwise, pass an array of SecCertificateRef objects.
=> Removed ambiguous array creation in AFSecurityPolicy

Tests/Tests/AFHTTPSessionManagerTests.m, Tests/Tests/AFImageDownloaderTests.m, Tests/Tests/AFNetworkActivityManagerTests.m, Tests/Tests/AFNetworkReachabilityManagerTests.m, Tests/Tests/AFTestCase.h, Tests/Tests/AFTestCase.m, Tests/Tests/AFUIActivityIndicatorViewTests.m, Tests/Tests/AFUIButtonTests.m, Tests/Tests/AFUIImageViewTests.m, Tests/Tests/AFUIRefreshControlTests.m, Tests/Tests/AFUIWebViewTests.m, Tests/Tests/AFURLSessionManagerTests.m
Since literally every call to `waitForExpectationsWithCommonTimeoutUsingHandler` is passing a `nil` parameter, I think there should be a convenient method for this. 
This simplify the waiting method when doing async test. I have a feeling that people would love this.
=> Add test method to wait for common timeout without handler

AFNetworking.xcodeproj/xcshareddata/xcschemes/AFNetworking OS X.xcscheme, AFNetworking.xcodeproj/xcshareddata/xcschemes/AFNetworking iOS.xcscheme, AFNetworking.xcodeproj/xcshareddata/xcschemes/AFNetworking tvOS.xcscheme, Tests/Tests/AFJSONSerializationTests.m, Tests/Tests/AFPropertyListRequestSerializerTests.m, Tests/Tests/AFTestCase.h, Tests/Tests/AFTestCase.m
Editing the scheme and checking the `HTTPBIN_BASE_URL` box enables running the test suites on a default local installation of httpbin.
=> Enable custom httpbin URL with HTTPBIN_BASE_URL environment variable

Tests/Tests/AFNetworkReachabilityManagerTests.m
Hopefully these changes will fix the domain reachability tests.
=> Fix reachability tests

AFNetworking/AFURLResponseSerialization.h, AFNetworking/AFURLResponseSerialization.m
The `stringEncoding` property is never used. It was probably inroduced by error in 9a40c0dc0f27e9a547fb173a0b1b5a06072e91f9. It was probably a copy/paste error as the same property also exists on `AFHTTPRequestSerializer` where it’s actually used.
=> Deprecate the unused stringEncoding property of AFHTTPResponseSerializer

AFNetworking.xcodeproj/project.pbxproj, AFNetworking/AFURLResponseSerialization.h, Tests/Tests/AFXMLDocumentResponseSerializerTests.m, Tests/Tests/AFXMLParserResponseSerializerTests.m
Inspired by 290ec35a4a9101322253f05d2c1e1319e9b4b248, this adds tests for `AFXMLParserResponseSerializer` and `AFXMLDocumentResponseSerializer`. This also fixes an error in `AFXMLDocumentResponseSerializer` documentation.
=> Add XMLParser/XMLDocument serializer tests

AFNetworking/AFURLResponseSerialization.h
This clarify the data encoding needed for `AFJSONResponseSerializer` to successfully parsing the response as JSON object.
=> Clarify documentation for supported encodings in AFJSONResponseSerializer

Tests/Tests/AFAutoPurgingImageCacheTests.m, Tests/Tests/AFImageDownloaderTests.m, UIKit+AFNetworking/AFAutoPurgingImageCache.h, UIKit+AFNetworking/AFAutoPurgingImageCache.m, UIKit+AFNetworking/AFImageDownloader.h, UIKit+AFNetworking/AFImageDownloader.m
- Allow user to config `AFImageDownloader +defaultURLCache`. Currently, the values are hardcoded 20Mb mem, 150Mb disk.
- Provide a hook in `AFAutoPurgingImageCache` so `UIImages` can be filtered before cached. Ideally, one could filter out `UIImage` that exceeds certain *raster* size.
A `UICollectionView` shows thumbnails of JPGs. Tapping any `UICollectionViewCell` opens a full size `UIImageView` that displays the full size JPG.
Under thew current implementation, large JPGs boot out thumbnails.
Hence JPGs and thumbnails are downloaded almost always as both caches keep getting recycled.
SO: https://stackoverflow.com/questions/41939774/how-to-limit-size-of-image-disk-cache-using-afnetworking/45329948#45329948
See AFNetworking/issues/4009
=> Config AFImageDownloader NSURLCache and ask AFImageRequestCache implementer if an image should be cached

AFNetworking/AFURLSessionManager.m, Tests/Tests/AFURLSessionManagerTests.m
This is the same as [@funnel20](https://github.com/funnel20)’s [PR](https://github.com/AFNetworking/AFNetworking/pull/4120), but made off of the latest `master` so hopefully the coverage bot will have fewer changes to look at.
=> Fix analyzer warning for upload task creation

AFNetworking/AFURLSessionManager.m
This PR fixes the last remaining issue encountered by running `pod lib lint`.
=> Use @available if available to silence a warning.

fastlane/Fastfile
After [this PR](https://github.com/AFNetworking/fastlane/pull/10), we should not be seeing the same CI errors we are currently seeing—we were using a deprecated logging method.
=> Update Fastlane Configuration

AFNetworking/AFURLSessionManager.m
The trailing brace within the #ifdef was confusig Xcode parsing the structure of the file. Fixes #4162.
=> Move a brace to make Xcode happy.

AFNetworking/AFNetworkReachabilityManager.h, AFNetworking/AFNetworkReachabilityManager.m, Tests/Tests/AFNetworkReachabilityManagerTests.m
See #4154—this is just cherry-picking it onto `master`. Closes #4163. Closes #4154.
=> Remove conflicting nullable specifier on init

Tests/Tests/AFURLSessionManagerTests.m, UIKit+AFNetworking/AFAutoPurgingImageCache.m, UIKit+AFNetworking/AFImageDownloader.m, UIKit+AFNetworking/UIImage+AFNetworking.h, UIKit+AFNetworking/UIWebView+AFNetworking.m
1. apple documented coding guidelines, which uses (space after -)
2. fix asterisk location in method declaration
https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingBasics.html#//apple_ref/doc/uid/20001281-BBCHBFAH
=> fix space used in Objective-C method (coding style)

AFNetworking/AFURLResponseSerialization.m, Tests/Tests/AFJSONSerializationTests.m
I added a test case that causes `AFJSONObjectByRemovingKeysWithNullValues` to return a JSON object containing `NSNull`s in arrays, and added check against `NSNull` before adding to the response array. Let me know if I can clarify anything. You can see a real-world test case here: https://github.com/artsy/eigen/pull/2423/files#diff-99f40649a0fc5dfc78a7014cefddddc5R104
=> Modifies AFJSONObjectByRemovingKeysWithNullValues to remove NSArray null objects

AFNetworking/AFURLSessionManager.m
crashes when calling to a released block pointer
A security weakness was detected as a result of detection by Facebook's infer.
You can trigger a crash by sending nil to the url_session_manager_create_task_safely function as a debugger.
=> Fix AFURLSessionManager security weakness

UIKit+AFNetworking/AFImageDownloader.m
There is a race condition in -[AFImageDownloader downloadImageForURLRequest:withReceiptID:success:failure:] that can cause a crash.
#3876
The race condition can be seen with the Xcode Thread Sanitizer on and the project downloading and cancelling images quickly. 
In particular I noticed this downloading images for UITableViewCells and scrolling through the tableView.
#3984 
I think the main issue here is that `mergedTasks` is always updated on `synchronizationQueue` and it is being accessed on `responseQueue`. So there could be a change to the dictionary on a different thread.
=> Safely get mergedTasks On responseQueue

AFNetworking/AFURLResponseSerialization.h, AFNetworking/AFURLResponseSerialization.m
Good morning! I came across a use case in unit testing (see [this discussion](https://github.com/artsy/eigen/pull/2423#issuecomment-330227309) for specifics) when accessing the `AFJSONObjectByRemovingKeysWithNullValues` would be really useful. I'd like to propose exposing this function publicly so that network response stubbing in unit tests can behave as closely as possible to network response serialization in production. Let me know if I can clarify anything – thanks!
=> Exposes C function prototype

AFNetworking/AFHTTPSessionManager.h, AFNetworking/AFHTTPSessionManager.m, Tests/Tests/AFHTTPSessionManagerTests.m, Tests/Tests/AFNetworkActivityManagerTests.m
It would be nice to have an option to set HTTP headers per request when using AFHTTPSessionManager. 
Currently it's only possible to set the default headers on the request serializer which are used for every request done by the http session manager instance. The problem occurs when you would like to send different headers for different requests which cannot be done in a clean way using AFHTTPSessionManager.
Setting headers per request can only be implemented by using AFURLSessionManager or by subclassing/extending AFHTTPSessionManager, which seems to be inconvenient. 
Also Alamofire library for Swift supports the `headers per request`. It uses a bit different API (without the manager), however, it still seems to be inconsistent.
What do you think?
=> Support for setting headers per request when using AFHTTPSessionManager.

AFNetworking/AFNetworkReachabilityManager.h, AFNetworking/AFNetworkReachabilityManager.m, Tests/Tests/AFNetworkReachabilityManagerTests.m
there exists one problem [AFNetworkReachabilityManager shareManager] is singleton，but it also support that create other AFNetworkReachabilityManager by method ‘managerForDomain’ or ’managerForAddress‘. the two case is opposite.
so if network change, trigger posting AFNetworkingReachabilityDidChangeNotification , receiver can not know which is the actully sender，it will get multiple notification，then the receiver notification method would call multiple times, maybe cause continuously unexpectedly result.
=> Add an ability that notification-observer know which reachability it belongs

AFNetworking/AFHTTPSessionManager.h, AFNetworking/AFHTTPSessionManager.m
If you are consuming the AFHTTPSessionManager from swift on xcode 9.3 or above, this will crash when the response has no content (204). This is because of strict closure signature in swift.
=> AFNetworking 2.0 - Fix empty content crash on AFHTTPSessionManager.post

AFNetworking.podspec
- Fix podspec as library version supports iOS 8+ (in project) but podspec says iOS 7+
Note: We should release new version with this fix I think.
=> Fix podspec #trivial #important

AFNetworking/AFSecurityPolicy.m, AFNetworking/AFURLRequestSerialization.m, AFNetworking/AFURLResponseSerialization.m
Using`decodeObjectOfClass:[NSNumber class]` to decode an NSNumber object previously encoded by `encodeInteger` will fail.
=> Fix NSSecureCoding

AFNetworking/AFURLSessionManager.h
Fix wrong delegate method in `AFURLSessionManager` annotation
=> Fix wrong delegate method in `AFURLSessionManager` annotation

AFNetworking/AFURLRequestSerialization.m
I've been seeing a race condition where the `mutableHTTPRequestHeaders` has been deallocated inside of the block.
This PR pulls in changes from https://github.com/tmm1/AFNetworking/commit/32760e7a3a1cca2817ec498708182ec99584651a and then extends it based on [this comment](https://github.com/AFNetworking/AFNetworking/pull/3891#issuecomment-544337995).
It should help with https://github.com/AFNetworking/AFNetworking/issues/3636
and supersedes https://github.com/AFNetworking/AFNetworking/pull/3891.
=> Use a synchronous dispatch barrier block for mutable header writes

AFNetworking/AFSecurityPolicy.h, AFNetworking/AFSecurityPolicy.m
Using `[NSBundle bundleForClass:[self class]]` is dangerous because the code will behave differently depending on how AFNetworking is integrated.
- If it is integrated as a static library (for example using CocoaPods), certificates will be searched in the main bundle.
- If it is integrated as a framework (for example using Carthage), certificates will be searched in the AFNetworking framework.
Even though this behavior is documented, this is dangerous. Using the main bundle makes the behavior deterministic.
Fixes #3575
=> Search for default pinned certificates in the main bundle

UIKit+AFNetworking/UIButton+AFNetworking.m, UIKit+AFNetworking/UIImageView+AFNetworking.m
example  UIImageView (AFNetworking)
in "sharedImageDownloader:"  self is [UIImageView class].
than i have a class like this     UserImageView : UIImageView ,  in "sharedImageDownloader:"  self is [UserImageView class].
[UIImageView class] != [UserImageView class]
so  call [UserImageView sharedImageDownloader] , the objc_getAssociatedObject(self, @selector(sharedImageDownloader)) returns value is always nil.
=> fix AssociatedObject bug

README.md
if you still use github as specs source in your podfile, you will encounter rate limitation at some point. you must use cocoapods cdn. 
see here for more info: https://blog.cocoapods.org/CocoaPods-1.7.2/
=> use cocoapods cdn instead of github as specs source

AFNetworking/AFURLSessionManager.m, Tests/Tests/AFURLSessionManagerTests.m
As #4365 had been merged, That is to say we don’t support below iOS 8 and neither do modern versions of Xcode. And the bug [http://openradar.appspot.com/radar?id=5871104061079552](http://openradar.appspot.com/radar?id=5871104061079552) had been fixed in iOS8,  So we should delete the static queue `af_url_session_manager_creation_queue` that isn't been used in `AFNetWorking`.
=> Delete unused `af_url_session_manager_creation_queue ` when don’t support below iOS 8

AFNetworking/AFURLSessionManager.h, AFNetworking/AFURLSessionManager.m, Tests/Tests/AFHTTPSessionManagerTests.m
Here’s another take at fixing #3165 which, unlike #3191, should not introduce a security flaw!
I will explain what I did and why in greater details later but I’m already submitting this pull request to see if all tests pass on Travis.
I’ll also create a better error with a full userInfo dictionary, so please don’t merge this yet.
=> Pinning failure better error

AFNetworking.podspec
- Removed unnecessary `submodules` parameter from `source` attribute.
- Removed `requires_arc = true` since `requires_arc` defaults to `true`.
- Removed redundant [`public_header_files`](https://guides.cocoapods.org/syntax/podspec.html#public_header_files): if no public headers are specified then all the headers in `source_files` are considered public.
- Removed `prefix_header_contents`: since v4 requires Xcode 11+, these TARGET_OS definitions become unnecessary.
- Fixed bundle identifier for CocoaPods generated framework: change `org.cocoapods.AFNetworking` to `com.alamofire.AFNetworking`.
- Formatted podspec file: trimmed white space for blank lines.
=> Improve podspec

.github/issue_template.md, .github/pull_request_template.md, .github/stale.yml, README.md
- update readme - CocoaDocs are not used anymore
- add stale bot
- add issue template
- add pull request template
Re: Stale bot @jshier:
- please create new label "stale" that bot will use to mark stale Issues
- please configure the bot for this repo: https://github.com/apps/stale
After these two things ^^ are done, we can merge this.
More info: https://github.com/probot/stale
Thanks!
=> (Infra) Make infra changes to cleanup project and simplify its maintenance

AFNetworking.podspec
This warning appears when compiling **iOS/watchOS** AFNetworking installed from CocoaPods on Xcode 11.4.
Also from `pod lib lint`:
```
- NOTE  | xcodebuild:  warning: MobileCoreServices has been renamed. Use CoreServices instead. (in target 'AFNetworking' from project 'Pods')
```
**Why no warning on tvOS?**
Because we did not configure `frameworks` attribute for tvOS `Serialization` subspec:
```ruby
s.subspec 'Serialization' do |ss|
ss.source_files = 'AFNetworking/AFURL{Request,Response}Serialization.{h,m}'
ss.watchos.frameworks = 'MobileCoreServices', 'CoreGraphics'
ss.ios.frameworks = 'MobileCoreServices', 'CoreGraphics'
ss.osx.frameworks = 'CoreServices'
end
```
**Why Xcode issues this warning?**
- CocoaPods will add build flag `-framework "MobileCoreServices"` becuase there is …
=> Fix MobileCoreServices renamed warning, close #4520

AFNetworking.podspec
As discussed in https://github.com/AFNetworking/AFNetworking/pull/4528#discussion_r399952269 and https://github.com/AFNetworking/AFNetworking/pull/4530
Change framework bundle identifier For CocoaPods installation:
- iOS/macOS/tvOS: `com.alamofire.AFNetworking`
- watchOS: `com.alamofire.AFNetworking-watchOS`
=> Separate bundle identifier for watchOS target

UIKit+AFNetworking/UIKit+AFNetworking.h
For manual installation, adding `|| TARGET_OS_TV` conditional to expose some categories to tvOS.
=> Fix UIKit+AFNetworking.h

AFNetworking/AFURLSessionManager.m
Related to #4542, fixes #4541
We should evaluate server trust only when performing **server trust authentication**.
=> Fix condition of evaluateServerTrust

AFNetworking/AFHTTPSessionManager.m, Tests/Tests/AFHTTPSessionManagerTests.m
Related issue: https://github.com/AFNetworking/AFNetworking/issues/4549
For configuring headers to an individual request, in general, we prefer to replace the default value, instead of appending things to the default value with a comma, right?
In my opinion, using `setValue` is more reasonable and clearer.
=> Replace instead of appending to the default header

Package.swift
Original Package.swift introduced in 4.0.0 didn't work due to an improper header search path.
This PR fixes the Package.swift file by setting the `publicHeadersPath` value correctly.
As explained [here](https://forums.swift.org/t/can-i-use-swift-package-manager-in-obj-c-code/35463/16), the `publicHeadersPath` value is relative to the target directory, not the package file, so it should've been `""` instead of `"AFNetworking"`.
Tested manually with a test project that was broken previously.
=> Fix SPM Usage

AFNetworking/AFHTTPSessionManager.h, AFNetworking/AFHTTPSessionManager.m, AFNetworking/AFURLRequestSerialization.h, AFNetworking/AFURLSessionManager.h, AFNetworking/AFURLSessionManager.m, Package.swift, Tests/Tests/AFHTTPSessionManagerTests.m, Tests/Tests/AFSecurityPolicyTests.m, Tests/Tests/AFTestCase.h, Tests/Tests/AFTestCase.m
#4541
This PR builds on #4542 and #4552 to fix the crash seen when attempting to create an error for a `nil` `SecTrustRef`. It combines both approaches:
- Ensure we only attempt to check the trusts when `[challenge.protectionSpace.authenticationMethod isEqualToString:NSURLAuthenticationMethodServerTrust]` is `YES`.
- When creating an error, ensure proper nullability checks when inserting values into the `userInfo` dictionary, as even in the `NSURLAuthenticationMethodServerTrust` case, the values can be `nil`.
This PR makes the previous 
```objc
static NSError * ServerTrustError(SecTrustRef serverTrust, NSURL *url)
```
convenience function into an internal method on `AFURLSessionManager`
```objc
- (nonnull NSError *)serverTrustErrorForServerTrust:(SecTrustRef)serverTrust url:(NSURL *)url` …
```
=> Fix ServerTrustError crash.

AFNetworking/AFURLSessionManager.h
https://github.com/AFNetworking/AFNetworking/issues/4573
`-setTaskDidReceiveAuthenticationChallengeBlock:` has been renamed to `-setAuthenticationChallengeHandler:` in v4, but the docblock still references the old method name.
=> Fix docblock

AFNetworking.xcodeproj/xcshareddata/xcschemes/AFNetworking tvOS.xcscheme
Disables Zombie Object diagnostics for tvOS scheme
Diagnostics shouldn't be enabled by default. Specifically, this causes the framework for tvOS to be build with Zombie Objects enabled when installed using Carthage. Zombie Objects prevent objects from ever being freed up, which means AFNetworking is (potentially) constantly leaking memory on tvOS.
To be perfectly honest, I can't find any documentation stating whether having Zombie Objects enabled in the scheme causes them to be enabled in the resulting binary, and I don't see anything indicating one way or the other. I could be totally wrong in how this is actually handled for release builds. I'm assuming it's safer to disable it, but I'm not certain how to empirically verify that.
I just unchecked the "Zombie Objects" diagnostics option …
=> Disable 'Zombie Objects' diagnostics for tvOS scheme

AFNetworking/AFURLRequestSerialization.m
It's better to loop `mutableObservedChangedKeyPaths` directly: change loop count from `AFHTTPRequestSerializerObservedKeyPaths().count` (all) to `self.mutableObservedChangedKeyPaths.count` (actually needed).
Related PR https://github.com/AFNetworking/AFNetworking/pull/4253
=> Improve for-loop observed keyPaths for request serializer

AFNetworking/AFNetworkReachabilityManager.m
Close #4223, related https://github.com/Alamofire/Alamofire/pull/3207
Background queues may stop execution altogether in low power mode, so utility mode is recommended.
This PR changes `DISPATCH_QUEUE_PRIORITY_BACKGROUND` to `DISPATCH_QUEUE_PRIORITY_LOW` (maps to the `QOS_CLASS_UTILITY` class) for `SCNetworkReachabilityGetFlags()` in the method `-[AFNetworkReachabilityManager startMonitoring]`.
`DISPATCH_QUEUE_PRIORITY_BACKGROUND` -> `DISPATCH_QUEUE_PRIORITY_LOW`
None, there's no way to test this behavior.
=> Use low priority queue instead of background for SCNetworkReachabilityGetFlags()

Tests/Tests/AFHTTPSessionManagerTests.m
postmanlabs/httpbin#617
This PR replaces the httpbin.org service with [httpbingo.org](https://httpbingo.org) for the redirect test, because currently httpbin's redirect is returning a 404 response.
Change the request URL in `testThatRedirectBlockIsCalledWhen302IsEncountered` from `<HTTPBIN_BASE_URL>/redirect/1` to `https://httpbingo.org/redirect/1`.
All tests can pass now.
=> Fix redirect test: use httpbingo service instead
