AFNetworking/AFNetworking

UIKit+AFNetworking/UIRefreshControl+AFNetworking.h
=> fix a typo in comment

UIKit+AFNetworking/UIWebView+AFNetworking.m
=> fix UIWebView+AFNetworking crash

UIKit+AFNetworking/UIImageView+AFNetworking.h
Was reading the docs for `UIImageView+AFNetworking` this morning and stumbled across this _very_ minor typo. Not sure whether pull requests are accepted for such small changes, but though I'd send one along nonetheless.
Thanks for the awesome library!
=> Minor Docs Change

Tests/Tests/AFSecurityPolicyTests.m
Added
testDefaultPolicyMatchesTrustedCertificateWithMatchingHostnameAndRejects
Others which incorporates several tests to ensure the default mode of
security is at an expected level
Fixes #2633 
Please review!
=> Adding default security mode test to cover main settings

AFNetworking/AFSecurityPolicy.h
=> Fix documentation of AFSecurityPolicy

Tests/Tests/AFNetworkActivityManagerTests.m
Lets get this cleaned up so other branches quit getting false positives.
=> Fix Tests Randomly Failing for Reachability and Activity Manager

.travis.yml, AFNetworking/AFHTTPRequestOperation.h, AFNetworking/AFHTTPRequestOperationManager.h, AFNetworking/AFHTTPSessionManager.h, AFNetworking/AFNetworkReachabilityManager.h, AFNetworking/AFSecurityPolicy.h, AFNetworking/AFURLConnectionOperation.h, AFNetworking/AFURLRequestSerialization.h, AFNetworking/AFURLResponseSerialization.h, AFNetworking/AFURLSessionManager.h, AFNetworking/AFURLSessionManager.m, Tests/Tests/AFURLSessionManagerTests.m, UIKit+AFNetworking/AFNetworkActivityIndicatorManager.h, UIKit+AFNetworking/UIActivityIndicatorView+AFNetworking.h, UIKit+AFNetworking/UIAlertView+AFNetworking.h, UIKit+AFNetworking/UIButton+AFNetworking.h, UIKit+AFNetworking/UIImageView+AFNetworking.h, UIKit+AFNetworking/UIProgressView+AFNetworking.h, UIKit+AFNetworking/UIRefreshControl+AFNetworking.h, UIKit+AFNetworking/UIWebView+AFNetworking.h
Cleans up #2706 and #2566 and adds nullability to all of the header files.
=> Adding nullability

UIKit+AFNetworking/UIKit+AFNetworking.h
Removing #import "UIKit+AFNetworking.h" from header UIKit+AFNetworking.h
=> Removing self import

README.md
=> Improve documentation around Reachability. (In progress)

AFNetworking.podspec, AFNetworking/AFHTTPSessionManager.h, AFNetworking/AFHTTPSessionManager.m, AFNetworking/AFNetworkReachabilityManager.h, AFNetworking/AFNetworkReachabilityManager.m, AFNetworking/AFNetworking.h, AFNetworking/AFSecurityPolicy.m, AFNetworking/AFURLRequestSerialization.h, AFNetworking/AFURLRequestSerialization.m, AFNetworking/AFURLResponseSerialization.m, AFNetworking/AFURLSessionManager.h, AFNetworking/AFURLSessionManager.m, Example/AFNetworking iOS Example.xcodeproj/project.pbxproj, Example/AFNetworking watchOS Extension/Assets.xcassets/README__ignoredByTemplate__, Example/AFNetworking watchOS Extension/ExtensionDelegate.h, Example/AFNetworking watchOS Extension/ExtensionDelegate.m, Example/AFNetworking watchOS Extension/Info.plist, Example/AFNetworking watchOS Extension/InterfaceController.h, Example/AFNetworking watchOS Extension/InterfaceController.m, Example/AFNetworking watchOS/Assets.xcassets/AppIcon.appiconset/Contents.json, Example/AFNetworking watchOS/Base.lproj/Interface.storyboard, Example/AFNetworking watchOS/Info.plist, UIKit+AFNetworking/UIKit+AFNetworking.h
Including AFNetworking in a WatchKit 2 project results in a SystemConfiguration.h file not found error. 
I am seeing this in Xcode 7 / WatchOS 2 (beta 3)
=> WatchKit support

AFNetworking/AFURLRequestSerialization.h, AFNetworking/AFURLSessionManager.h
=> Added missing __nullable attributes

README.md
Apple changed the format WWDC video URLs.
=> Fix README link to WWDC session

AFNetworking/AFURLConnectionOperation.m, AFNetworking/AFURLRequestSerialization.m, AFNetworking/AFURLResponseSerialization.m, AFNetworking/AFURLSessionManager.m, Example/AFNetworking OS X Example.xcodeproj/project.pbxproj, Example/AFNetworking OS X Example.xcodeproj/xcshareddata/xcschemes/AFNetworking Example.xcscheme, Example/AFNetworking iOS Example.xcodeproj/xcshareddata/xcschemes/AFNetworking iOS Example.xcscheme, Example/AFNetworking iOS Example.xcodeproj/xcshareddata/xcschemes/AFNetworking watchOS.xcscheme, Example/AFNetworking iOS Example.xcodeproj/xcshareddata/xcschemes/Today Extension.xcscheme, Example/Mac-Info.plist, Tests/AFNetworking Tests.xcodeproj/project.pbxproj, Tests/AFNetworking Tests.xcodeproj/xcshareddata/xcschemes/OS X Tests.xcscheme, Tests/AFNetworking Tests.xcodeproj/xcshareddata/xcschemes/iOS Tests.xcscheme, Tests/Tests/AFUIImageViewTests.m
Built on top of a rebased #3019
=> Removed Project Warnings (and updated version of #3019)

README.md
Created with https://github.com/dkhamsing/frankenstein
=> FIXED URLs that were redirecting in the README

AFNetworking/AFNetworkReachabilityManager.h, AFNetworking/AFNetworkReachabilityManager.m
=> Added a method to create a unique reachability manager

AFNetworking/AFURLRequestSerialization.h, AFNetworking/AFURLResponseSerialization.h
=> Fixed swift interop issue with throws and Request/Response serialization

AFNetworking/AFNetworkReachabilityManager.m
=> Suppressed false positive memory leak warning in Reachability Manager

AFNetworking/AFNetworkReachabilityManager.m, Tests/Tests/AFNetworkReachabilityManagerTests.m
=> Fixed race condition in reachability callback delivery

AFNetworking/AFURLRequestSerialization.h, AFNetworking/AFURLResponseSerialization.h, AFNetworking/AFURLSessionManager.h
=> Restored Xcode 6 compatibility 

AFNetworking/AFURLSessionManager.m
=> Fixed race condition crash from Resume/Suspend task notifications

AFNetworking/AFHTTPSessionManager.h, Tests/Tests/AFHTTPSessionManagerTests.m
=> Added nullability attributes to response object in success block

AFNetworking/AFHTTPSessionManager.h, AFNetworking/AFHTTPSessionManager.m, AFNetworking/AFNetworkReachabilityManager.h, AFNetworking/AFURLRequestSerialization.m, AFNetworking/AFURLSessionManager.h, UIKit+AFNetworking/AFAutoPurgingImageCache.m, UIKit+AFNetworking/AFImageDownloader.m
* Cleanup `NS_DESIGNATED_INITIALIZER`
* Cleanup `OS_OBJECT_HAVE_OBJC_SUPPORT `
=> Removed code supporting conditional compilation for unsupported development configurations.

AFNetworking.xcodeproj/project.pbxproj, AFNetworking/AFURLRequestSerialization.m, Example/AFNetworking Example.xcodeproj/project.pbxproj, Tests/Tests/AFHTTPSessionManagerTests.m
More cleanup for OS X 10.9 / iOS 7.0
And more tests too. 😃
=> Removed AFBase64EncodedStringFromString static function

.travis.yml, fastlane/Fastfile
Taking @0xced's work from #3184, and just using codecov for now.
=> Added support for Codecov.io

AFNetworking/AFURLSessionManager.m, Tests/Tests/AFURLSessionManagerTests.m
Taking #3205 and adding a test to it.
Thanks @nikitahils!
=> Improved task creation performance for iOS 8+

README.md
This URL threw me off when I first read it, figured this way will reduce confusion for others.
=> Changing confusing URL in Readme for data task

AFNetworking.xcodeproj/project.pbxproj, Tests/Tests/AFUIWebViewTests.m, UIKit+AFNetworking/UIWebView+AFNetworking.m
=> Fixed crash when passing nil/null for progress in UIWebView extension

Tests/Tests/AFImageDownloaderTests.m, UIKit+AFNetworking/AFImageDownloader.m
=> Fixed image downloading cancellation race condition

UIKit+AFNetworking/AFAutoPurgingImageCache.m
Fixed image memory calculation
=> Fixed image memory calculation

fastlane/README.md
=> Fix spelling

AFNetworking/AFURLRequestSerialization.m, Tests/Tests/AFHTTPRequestSerializationTests.m
=> Removed trailing question mark in query string if parameters are empty

AFNetworking/AFURLSessionManager.m
The impetus for this change was a bug related to:
https://github.com/AFNetworking/AFNetworking/issues/3380
Which points to an issue where AFURLSessionManager could get in a state where it does not inform the AFURLSessionManagerTaskDelegate to un-observe cancelled (or otherwise completed) tasks before they are deallocated.
While the above issue is specific to background tasks/sessions, we have observed it on sessions with default configurations as well.
Instead of debugging the KVO issues, I decided to replace the KVO code with in favor of the appropriate NSURLSession delegate methods.
Running all unit tests shows that this approach appears to be working.
The pull request that made this change (https://github.com/AFNetworking/AFNetworking/pull/3187) mentions that its goal was to remove the …
=> Remove KVO of progress in favor of using the NSURLSession delegate APIs

.travis.yml
Workaround a bundler issue which is tracked on https://github.com/bundler/bundler/pull/4981
=> Fix Travis build failures because of fastlane/bundler error

AFNetworking/AFURLSessionManager.m
Please see both commit comments for a full explanation.
=> Fixed potential KVO crasher for URL Session Task delegates

README.md
User can find the LICENSE address conveniently
=> add the link for LICENSE

AFNetworking/AFURLRequestSerialization.m
Adding user agent information to the request serializer for tvOS devices.
=> Adding tvOS User Agent

AFNetworking/AFHTTPSessionManager.h
Change -dataTaskWithHTTPMethod visibility from private to public.
#2379, #2380, #2404, #2862, #3361
=> Change dataTaskWithHTTPMethod visibility to public

AFNetworking/AFURLSessionManager.m, CHANGELOG.md, README.md
This PR prepares the 4.0.0 release.
=> Prepare 4.0.0.

AFNetworking/AFURLRequestSerialization.h
=> Correct AFURLRequestSerialization comments.

AFNetworking.xcodeproj/project.pbxproj
make them available to Xcode editor
=> Add assistant files to xcode project (not target)
